# Generated by Django 4.2.4 on 2023-08-07 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('attack', models.IntegerField()),
                ('skill_percentage', models.FloatField(verbose_name='Skill Percentage')),
                ('add_damage', models.FloatField(verbose_name='Additional Percentage')),
                ('crit_dmg', models.FloatField(verbose_name='Crit Damage')),
            ],
        ),
    ]
